export const LEVELS = [
  { id: 'easy', icon: '😀', value: 'easy' },
  { id: 'medium', icon: '🥲', value: 'medium' },
  { id: 'hard', icon: '😏', value: 'hard' },
  { id: 'legendary', icon: '🥵', value: 'legendary' },
];

export const ICONS = [
  { id: 'PL', icon: '🇵🇱' },
  { id: 'AD', icon: '🇦🇩' },
  { id: 'AE', icon: '🇦🇪' },
  { id: 'AF', icon: '🇦🇫' },
  { id: 'AG', icon: '🇦🇬' },
  { id: 'AI', icon: '🇦🇮' },
  { id: 'AL', icon: '🇦🇱' },
  { id: 'AM', icon: '🇦🇲' },
  { id: 'AO', icon: '🇦🇴' },
  { id: 'AQ', icon: '🇦🇶' },
  { id: 'AR', icon: '🇦🇷' },
  { id: 'AS', icon: '🇦🇸' },
  { id: 'AT', icon: '🇦🇹' },
  { id: 'AU', icon: '🇦🇺' },
  { id: 'AW', icon: '🇦🇼' },
  { id: 'AX', icon: '🇦🇽' },
  { id: 'AZ', icon: '🇦🇿' },
  { id: 'BA', icon: '🇧🇦' },
  { id: 'BB', icon: '🇧🇧' },
  { id: 'BD', icon: '🇧🇩' },
  { id: 'BE', icon: '🇧🇪' },
  { id: 'BF', icon: '🇧🇫' },
  { id: 'BG', icon: '🇧🇬' },
  { id: 'BH', icon: '🇧🇭' },
  { id: 'BI', icon: '🇧🇮' },
  { id: 'BJ', icon: '🇧🇯' },
  { id: 'BL', icon: '🇧🇱' },
  { id: 'BM', icon: '🇧🇲' },
  { id: 'BN', icon: '🇧🇳' },
  { id: 'BO', icon: '🇧🇴' },
  { id: 'BQ', icon: '🇧🇶' },
  { id: 'BR', icon: '🇧🇷' },
  { id: 'BS', icon: '🇧🇸' },
  { id: 'BT', icon: '🇧🇹' },
  { id: 'BV', icon: '🇧🇻' },
  { id: 'BW', icon: '🇧🇼' },
  { id: 'BY', icon: '🇧🇾' },
  { id: 'BZ', icon: '🇧🇿' },
  { id: 'CA', icon: '🇨🇦' },
];
